# Generated by Django 3.2.5 on 2021-10-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=350)),
                ('module_name', models.CharField(max_length=350)),
                ('senario', models.CharField(max_length=350)),
                ('description', models.CharField(max_length=350)),
                ('input_data', models.CharField(max_length=350)),
                ('type_of_exception', models.CharField(max_length=350)),
                ('pre_condition', models.CharField(max_length=350)),
                ('expected_actual_result', models.CharField(max_length=350)),
                ('status', models.CharField(max_length=300)),
                ('date_of_creation', models.DateField()),
                ('tester_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
