# Generated by Django 3.2.5 on 2021-11-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_alter_testcase_date_of_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcase_id', models.IntegerField()),
                ('description', models.CharField(max_length=350)),
                ('path', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/')),
                ('severity', models.CharField(max_length=300)),
                ('priority', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
                ('bdate', models.DateTimeField()),
                ('tested_by_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='testcase',
            name='date_of_creation',
            field=models.DateField(),
        ),
    ]
