# Generated by Django 3.2.5 on 2021-11-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0003_auto_20211101_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='severity',
            new_name='sevearity',
        ),
    ]
