# Generated by Django 3.2.5 on 2021-11-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0004_rename_severity_bug_sevearity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='bdate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='bug',
            old_name='image',
            new_name='screenshot',
        ),
        migrations.RenameField(
            model_name='bug',
            old_name='path',
            new_name='test_path',
        ),
    ]
