# Generated by Django 3.2.5 on 2021-11-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0005_auto_20211101_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='date',
            field=models.DateField(),
        ),
    ]
