# Generated by Django 3.2.5 on 2021-11-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0006_alter_bug_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_id', models.IntegerField()),
                ('status', models.CharField(max_length=300)),
                ('tested_by', models.EmailField(max_length=254)),
            ],
        ),
    ]
