# Generated by Django 3.2.5 on 2021-11-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0008_remove_status_bug_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
