# Generated by Django 3.2.5 on 2021-10-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('empname', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('dateofjoin', models.DateField()),
                ('salary', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
    ]
