# Generated by Django 3.2.5 on 2021-10-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsapp', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('technology', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('manager', models.CharField(max_length=100)),
            ],
        ),
    ]
